apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: secagent-staging
resources:
  - reference-corpus-pvc.yaml
  - reference-expander-configmap.yaml
  - reference-corpus-expander.cronjob.yaml
  - reference-expander-servicemonitor.yaml
# Optional: create secret out-of-band for GH_TOKEN corpus export
#  - reference-expander-secret.yaml
